kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-roks-cluster-pipeline
  namespace: CLUSTER_NAME_PLACEHOLDER
rules:
  - verbs:
      - ''
    apiGroups:
      - ''
    resources:
      - ''