kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-roks-cluster-pipeline
  namespace: CLUSTER_NAME_PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: new-roks-cluster-pipeline