apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: CLUSTER_NAME_PLACEHOLDER
  namespace: CLUSTER_NAME_PLACEHOLDER
spec:
  clusterName: CLUSTER_NAME_PLACEHOLDER
  clusterNamespace: CLUSTER_NAME_PLACEHOLDER
  clusterLabels:
    name: CLUSTER_NAME_PLACEHOLDER
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
    argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true