apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: CLUSTER_NAME_PLACEHOLDER
  labels:
    name: CLUSTER_NAME_PLACEHOLDER
    cloud: auto-detect
    vendor: auto-detect
  annotations: {}
spec:
  hubAcceptsClient: true